audio_visualization:
  mel_buffer_scale: 20
  audio_visual_span: 20
  seconds_in_view: 120
  cmap : 'copper'
mel_spectrogram:
  db_high: 80
  db_low: 0
  f_high: 20000
  f_low: 20
  hop_length: 512
  n_fft: 8192
  maxpower : 2000
video:
  frame_rate: 30
  height: 200
  width: 1280
