audio_visualization:
  audio_visual_span: 1
  cmap: magma
  max_spectrogram_width: 65000
  playhead_position: 0.5  # Centered horizontally
  playhead_rgba: [255,255,255,192] # white, slightly transparent
  playhead_width: 2 # Assuming pixels for thick
  playhead_section_rgba : [0,0,0,0]
  seconds_in_view: 300
  profiling_chunk_duration: 900
mel_spectrogram:
  db_high: 0
  db_low: -80
  f_high: 22000
  f_low: 20
  hop_length: 512
  n_fft: 2048
  n_mels: 400
video:
  frame_rate: 30
  height: 200
  width: 800
overlays:
  frequency_axis:
      freq_hz : [100, 1000, 3000, 5000, 8000]
      axis_position: 0.5  # Centered horizontally
      axis_rgba: [255,255,255,192] # white, slightly transparent