audio_visualization:
  audio_visual_span: 1
  cmap: magma
  max_spectrogram_width: 65000
  seconds_in_view: 20
  profiling_chunk_duration: 900
mel_spectrogram:
  db_high: 0
  db_low: -80
  f_high: 22000
  f_low: 50
  hop_length: 512
  n_fft: 2048
  n_mels: 200
video:
  frame_rate: 30
  height: 400
  width: 800
overlays:
  frequency_axis:
    enabled : True
    freq_hz : [100, 1000, 3000, 5000, 8000, 20000]
    axis_position: 0.5  # Centered horizontally
    axis_rgba: [255,255,255,192] # white, slightly transparent
  playhead:
    enabled : True
    playhead_position: 0.5  # Centered horizontally
    playhead_rgba: [255,255,255,192] # white, slightly transparent
    playhead_width: 2 # Assuming pixels for thick
    playhead_section_rgba : [0,0,0,0]
  labels:
    enabled: True
    rgba: [255,255,255,192] # white, slightly transparent
    items:
      - type : brace
        freq: [0, 200]
        text: traffic
        rgba: [255, 255, 255, 128]
        x_pos_ratio : 0.5
        v_align : top
      - type : brace
        freq: [8000, 8500]
        text: insects
        rgba: [255, 255, 255, 128]
        x_pos_ratio : 0.5
        v_align : bottom
      - type : text 
        time: [5, 10]
        freq: [2000, 2500]
        text: bar
        rgba: [255, 255, 255, 128]
      - type : box
        time: [13.3, 13.5]
        freq: [400, 2100]
        text: "POI"
        rgba: [255, 255, 255, 128]    