audio_visualization:
  cmap: bone
  mel_buffer_multiplier: 1
  playhead_position: 0.50
  seconds_in_view: 60
mel_spectrogram:
  db_high: 0
  db_low: -70
  f_high: 30000
  f_low: 50
  hop_length: 512
  n_fft: 4096
video:
  frame_rate: 30
  height: 200
  width: 400
