audio_visualization:
  cmap: bone
  audio_visual_span: 3
  playhead_position: 0.25
  seconds_in_view: 10
mel_spectrogram:
  db_high: 0
  db_low: -70
  f_high: 22000
  f_low: 50
  hop_length: 256
  n_fft: 2048
video:
  frame_rate: 30
  height: 200
  width: 400
