audio_visualization:
  audio_visual_span: 1
  cmap: magma
  max_spectrogram_width: 5000
  playhead_position: 0.5  # Centered horizontally
  playhead_color: "#FFFFFF"  # White, in HEX format
  playhead_opacity: 0.2  # Slightly transparent
  playhead_width: 2 # Assuming pixels for thick
  seconds_in_view: 60
  profiling_chunk_duration: 60 
mel_spectrogram:
  db_high: 0
  db_low: -70
  f_high: 22050
  f_low: 50
  hop_length: 512
  n_fft: 2048
  n_mels: 200
video:
  frame_rate: 30
  height: 200
  width: 800
