audio_visualization:
  audio_visual_span: 1
  cmap: magma
  max_spectrogram_width: 1000
  seconds_in_view: 60
  profiling_chunk_duration: 900
mel_spectrogram:
  db_high: 0
  db_low: -70
  f_high: 11025
  f_low: 20
  hop_length: 512
  n_fft: 2048
  n_mels: 300
video:
  frame_rate: 30
  height: 200
  width: 800
overlays:
  frequency_axis:
    enabled : False
    freq_hz : [100, 1000, 3000, 5000, 8000, 11000]
    axis_position: 0.5  # Centered horizontally
    axis_rgba: [255,255,255,192] # white, slightly transparent
  playhead:
    enabled : False
    playhead_position: 0.5  # Centered horizontally
    playhead_rgba: [255,255,255,192] # white, slightly transparent
    playhead_width: 2 # Assuming pixels for thick
    playhead_section_rgba : [0,0,0,0]