audio_visualization:
  audio_visual_span: 1
  cmap: magma
  max_spectrogram_width: 6000
  playhead_position: 0.25
  playhead_rgba:
  - 255
  - 255
  - 255
  - 192
  playhead_section_rgba:
  - 0
  - 0
  - 0
  - 0
  playhead_width: 2
  profiling_chunk_duration: 60
  seconds_in_view: 60
duration: 300.0
input: .\testing\test.wav
mel_spectrogram:
  db_high: 0
  db_low: -70
  f_high: 10000
  f_low: 50
  hop_length: 512
  n_fft: 2048
  n_mels: 400
output: output.mp4
overlays:
  frequency_axis:
    axis_position: 0.25
    axis_rgba:
    - 255
    - 255
    - 255
    - 192
    freq_hz:
    - 100
    - 1000
    - 3000
    - 5000
    - 8000
  playhead:
    enabled: true
    playhead_position: 0.5
    playhead_rgba:
    - 255
    - 255
    - 255
    - 192
    playhead_section_rgba:
    - 0
    - 0
    - 0
    - 0
    playhead_width: 2
overwrite: true
path: .\testing\test1
sr: 20050
start: 100.0
video:
  frame_rate: 30
  height: 200
  width: 800
